HW2/app.py
from flask import Flask
from routes.main_page_route import main_page_routes
from routes.attendance_route import attendance_routes
from routes.dept_route import dept_routes
from routes.student_route import student_routes

app = Flask(__name__)
app.register_blueprint(main_page_routes)
app.register_blueprint(attendance_routes)
app.register_blueprint(dept_routes)
app.register_blueprint(student_routes)

if __name__ == '__name__':
    app.run(debug=True)

HW2/routes/attendance_route.py
from flask import Blueprint, jsonify, request, render_template, redirect, url_for
from db.db import get_db_connection
from repos.attendance_repo import get_student_attendance, add_student_attendance, update_student_attendance, delete_student_attendance

attendance_routes = Blueprint('attendance_routes', __name__, url_prefix='/attendance')

@attendance_routes.route('/', methods=['GET'])
def get_student_attendance_route():
    db_conn = get_db_connection()
    student_attendances = get_student_attendance(db_conn)
    return render_template('attendance.html', student_attendances=student_attendances)

@attendance_routes.route("/", methods=['POST'])
def add_student_attendance_route():
    db_conn = get_db_connection()
    req = request.form

    student_id = req['student_id']
    name = req['name']

    res = add_student_attendance(db_conn, student_id, name)
    if res:
        return jsonify({"message": "Add OK"}), 201
    
    return jsonify({"error": "Add error"}), 400

@attendance_routes.route("/update/<id>", methods=['PUT'])
def update_student_attendance_route(id):
    db_conn = get_db_connection()
    req = request.get_json()
    student_id = req['student_id']
    name = req['name']

    res = update_student_attendance(db_conn, id, student_id, name)
    if res:
        return jsonify({"message": "Update OK"}), 204

    return jsonify({"error": "Update error"}), 400

@attendance_routes.route("/delete/<id>", methods=['DELETE'])
def delete_student_attendance_route(id):
    db_conn = get_db_connection()
    res = delete_student_attendance(db_conn, id)
    if res:
        return jsonify({"message": "Delete OK"}), 204

    return jsonify({"error": "Delete error"}), 400

HW2/routes/dept_route.py
from flask import Blueprint, jsonify, request, render_template, redirect, url_for
from db.db import get_db_connection
from repos.dept_repo import get_all_dept, add_dept, update_dept, delete_dept

dept_routes = Blueprint('dept_routes', __name__, url_prefix='/dept')

@dept_routes.route('/', methods=['GET'])
def get_all_dept_route():
	db_conn = get_db_connection()
	depts = get_all_dept(db_conn)
	return render_template('department.html', depts=depts)

@dept_routes.route("/", methods=['POST'])
def add_dept_route():
    db_conn = get_db_connection()
    req = request.form

    dept_id = req['dept_id']
    name = req['name']
    num_of_faculty = req['num_of_faculty']

    res, error_message = add_dept(db_conn, dept_id, name, num_of_faculty)
    if res:
        return redirect(url_for('dept_routes.get_all_dept_route'))
    
    return jsonify({"error": error_message}), 400

@dept_routes.route("/update/<id>", methods=['PUT'])
def update_dept_route(id):
    db_conn = get_db_connection()
    req = request.get_json()
    dept_id = req['dept_id']
    name = req['name']
    num_of_faculty = req['num_of_faculty']

    res, error_message = update_dept(db_conn, id, dept_id, name, num_of_faculty)
    if res:
        return {}, 204
    return jsonify({"error": error_message}), 400

@dept_routes.route("/delete/<id>", methods=['DELETE'])
def delete_dept_route(id):
    db_conn = get_db_connection()
    res = delete_dept(db_conn, id)
    if res:
        return {}, 204

    return {}, 400

HW2/routes/main_page_route.py
from flask import Blueprint, render_template
from db.db import get_db_connection
from repos.main_repo import get_join_data

main_page_routes = Blueprint('main_page_routes', __name__)

@main_page_routes.route('/', methods=['GET'])
def get_student_attendance_route():
	db_conn = get_db_connection()
	join_data = get_join_data(db_conn)

	return render_template('main_page.html', data=join_data)

HW2/routes/student_route.py
from flask import Blueprint, request, jsonify, render_template, redirect, url_for
from db.db import get_db_connection
from repos.student_repo import get_all_student, add_student, update_student, delete_student

student_routes = Blueprint('student_routes', __name__, url_prefix='/student')

@student_routes.route('/', methods=['GET'])
def get_all_student_route():
	db_conn = get_db_connection()
	students = get_all_student(db_conn)
	return render_template('student.html', students=students)

@student_routes.route("/", methods=['POST'])
def add_student_route():
    db_conn = get_db_connection()
    req = request.form

    student_id = req['student_id']
    name = req['name']
    dept_id = req['dept_id']
    dob = req['dob']

    res, error_message = add_student(db_conn, student_id, name, dept_id, dob)
    if res:
        return jsonify({"message": "Add OK"}), 201
    
    return jsonify({"error": error_message}), 400

@student_routes.route("/update/<id>", methods=['PUT'])
def update_student_route(id):
    db_conn = get_db_connection()
    req = request.get_json()
    print("debug req", req)

    student_id = req['student_id']
    name = req['name']
    dept_id = req['dept_id']
    dob = req['dob']
    
    res, error_message = update_student(db_conn, id, student_id, name, dept_id, dob)
    if res:
        return jsonify({"message": "Update OK"}), 204

    return jsonify({"error": error_message}), 400

@student_routes.route("/delete/<id>", methods=['DELETE'])
def delete_student_route(id):
    db_conn = get_db_connection()
    res = delete_student(db_conn, id)
    if res:
        return jsonify({"message": "Delete OK"}), 204
    
    return {}, 400

HW2/templates/attendance.html
{% extends "main_layout.html" %}

{% block title %}Attendance{% endblock %}

{% block content %}
<div style="width: 80%; margin-top: 16px;">
  <h2>Student Attendance</h2>
  <div id="notification" style="display: none;"></div>
  <form id="form" method="POST" onsubmit="handleSubmitForm(event)">
    <div style="display: flex; align-content: center;">
      <div style="display: flex; gap: 16px;">
        <div>
          <label for="student_id">Student ID:</label>
          <input
            style="max-width: 200px;"
            class="input-field"
            type="text"
            id="student_id"
            name="student_id"
            required
          />
        </div>
        <div>
          <label for="name">Name:</label>
          <input class="input-field" type="text" id="name" name="name" required />
        </div>
      </div>
    </div>
    <button class="submit-button" type="submit">Submit</button>
  </form>
  <br/>
  {% if student_attendances|length > 0 %}
    <table border="1" class="table-class">
      <thead>
        <tr>
          <td>ID</td>
          <td>Student ID</td>
          <td>Student Name</td>
          <td>Check-in time</td>
        </tr>
      </thead>
      <tbody>
        {% for student_attendance in student_attendances%}
        <tr>
          <td>{{loop.index}}</td>
          <td 
            id="id-{{student_attendance['id']}}"
            style="padding-right: 8px"
          >
            {{student_attendance['student_id']}}
          </td>
          <td 
            id="name-{{student_attendance['id']}}"
            style="padding-right: 8px"
          >
            {{student_attendance['name']}}
          </td>
          <td style="width: 240px;">
            {{student_attendance['created_at']}}
          </td>
          <td style="width: 50px; ">
            <div id="button-{{student_attendance['id']}}" style="display: flex; justify-content: space-between; justify-self: center;">
              <i 
                class="fa-regular fa-pen-to-square" 
                style="cursor: pointer; margin-right: 8px;" 
                type="button"
                onclick="onEditButtonClick('{{student_attendance['id']}}')"
              ></i>
              <i 
                class="fa-solid fa-trash"
                style="cursor: pointer;" 
                type="button"
                uk-toggle="target: #modal-center"
                onclick="storeRecordId('{{student_attendance['id']}}')"
              ></i>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No departments available.</p>
  {% endif %}
  <div id="modal-center" uk-modal>
    <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical"">
      <h2 style="justify-self: center;">Delete this record?</h2>
      <p class="uk-text-right">
        <button class="uk-button uk-button-default uk-modal-close" type="button">Cancel</button>
        <button class="uk-button uk-button-danger" type="button" onclick="onDeleteButtonClick()">Delete</button>
      </p>
    </div>
  </div>
</div>
<script>
  var initButtonContainerInnerHTML;
  var initStudentIdRowInnerHTML;
  var initNameRowInnerHTML;
  var currentRecordId;

  function storeRecordId(id) {
    currentRecordId = id;
  }

  function closeNotification() {
    const notification = document.getElementById('notification');
    notification.style.display = 'none';
  }

  async function handleSubmitForm(event) {
    event.preventDefault(); // Prevent the form from submitting the traditional way

    const form = document.getElementById('form');
    const formData = new FormData(form);

    try {
      const response = await fetch(form.action, {
        method: 'POST',
        body: formData
      });

      if (!response.ok) {
        const notification = document.getElementById('notification');
        const errorData = await response.json();
        
        const studentIdContainer = document.getElementById('student_id');
        const studentNameContainer = document.getElementById('name');

        studentIdContainer.value = "";
        studentNameContainer.value = "";

        notification.style = `
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 10px;
          padding: 8px;
          background-color: rgb(255, 215, 222);
          color: red; 
          font-weight: bold;
        `;
        notification.innerHTML = `
          <p style="text-align: center; margin: 0 !important;">${errorData.error || 'An error occurred'}</p>
          <i 
            class="fa-regular fa-circle-xmark" 
            type="button"
            onclick="closeNotification()"
          ></i>
        `
        // 
      } else {
        // If successful, reload the page or update the UI as needed
        window.location.href = "{{ url_for('attendance_routes.get_student_attendance_route') }}";
      }
    } catch (error) {
      notification.style.display = 'block';
      notification.innerText = 'An error occurred while submitting the form.';
      console.error('Submission error:', error);
    }
  }

  function onEditButtonClick(id) {
    const buttonContainer = document.getElementById("button-" + id)
    initButtonContainerInnerHTML = buttonContainer.innerHTML;
    const studentIdRow = document.getElementById("id-" + id);
    initStudentIdRowInnerHTML = studentIdRow.innerHTML;
    const nameRow = document.getElementById("name-" + id);
    initNameRowInnerHTML = nameRow.innerHTML;
   
    buttonContainer.innerHTML = `
      <i 
        class="fa-solid fa-check"
        style="cursor: pointer; margin-right: 8px" 
        type="button"
        onclick="submitEdit(${id})"
      ></i>
      <i 
        class="fa-solid fa-xmark"
        style="cursor: pointer;" 
        type="button"
        onclick="closeEdit(${id})"
      ></i>
    `;

    studentIdRow.innerHTML = `
      <input 
        style="width: 100px;"
        class="input-field"
        type="text" 
        id="id-input-${id}" 
        value="${studentIdRow.innerText}"
      >
    `;

    nameRow.innerHTML = `
      <input 
        style="width: 100px;"
        class="input-field"
        type="text" 
        id="name-input-${id}" 
        value="${nameRow.innerText}"
      >
    `; 
  }

  function closeEdit(id) {
    const buttonContainer = document.getElementById("button-" + id)
    const studentIdRow = document.getElementById("id-" + id);
    const nameRow = document.getElementById("name-" + id);

    buttonContainer.innerHTML = initButtonContainerInnerHTML;
    studentIdRow.innerHTML = initStudentIdRowInnerHTML;
    nameRow.innerHTML = initNameRowInnerHTML;
  }

  function submitEdit(id) {
    const buttonContainer = document.getElementById("button-" + id)
    const studentId = document.getElementById("id-input-" + id).value;
    const name = document.getElementById("name-input-" + id).value;

    $.ajax({
      url: "/attendance/update/" + id,
      type: "PUT",
      contentType: "application/json",
      data: JSON.stringify({
        student_id: studentId,
        name: name,
      }),
      success: function () {
        location.reload();
        // alert("Attendance updated successfully!");
      },
      error: function (err) {
        alert("Error: Attendance update failed!");
        console.error("Error updating attendance:", err);
      },
    });
  }

  function onDeleteButtonClick() {
    $.ajax({
      url: "/attendance/delete/" + currentRecordId,
      type: "DELETE",
      contentType: "application/json",
      success: function () {
        location.reload();
        // alert("Attendance deleted successfully!");
      },
      error: function (err) {
        alert("Error: Attendance delete failed!");
        console.error("Error deleting attendance:", err);
      },
    });
  }
</script>
<style>
  
</style>
{% endblock %}

HW2/templates/main_layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}My Website{% endblock %}</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='styles.css') }}"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/1118529d73.js" crossorigin="anonymous"></script>
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.21.13/dist/css/uikit.min.css" />
    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.21.13/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.21.13/dist/js/uikit-icons.min.js"></script>
  </head>
  <body style="
    height: 100%;
    margin: 0;
  "> 
    <div style="
      display: flex;
      flex-direction: column;
      min-height: 100vh; 
    ">
      <header style="max-height: 40px">
        <div style="
          height: 40px;
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 8px;
        ">
          <div style="
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 6px; 
          ">
            <a href="/">
              <h2 style="color: black">stu.mgt</h2>
            </a>
            <a href="/attendance">
              <button className="bg-inherit">Attendance</button>
            </a>
            <a href="/student">
              <button className="bg-inherit">Student</button>
            </a>
            <a href="/dept">
              <button className="bg-inherit">Department</button>
            </a>
          </div>
          <!-- <div>Button</div> -->
        </div>
      </header>

      <main style="flex-grow: 1; padding: 16px">
        <div style="display: flex; width: 100%; justify-content: center">
          {% block content %}{% endblock %}
        </div>
      </main>

      <footer>
        <div style="
          display: flex;
          width: 100%;
          justify-content: center;
          height: 40px;
          align-items: center;"
        >
          <p>©2024 BaoLe. All rights reserved.</p>
        </div>
      </footer>
    </div>
  </body>
  
</html>

HW2/templates/main_page.html
{% extends "main_layout.html" %}

{% block title %}Student Management{% endblock %}

{% block content %}
<div style="width: 80%; margin-top: 16px;">
  <h2>Students' overall attendance record</h2>
  {% if data|length > 0 %}
    <table border="1" class="table-class" style="width: 100% !important;">
      <thead>
        <tr>
          <td>ID</td>
          <td>Student ID</td>
          <td>Student name</td>
          <td>Department ID</td>
          <td>Department name</td>
          <td>Latest attendance</td>
          <td>Attendance count</td>
        </tr>
      </thead>
      <tbody>
        {% for d in data%}
        <tr>
          <td>{{loop.index}}</td>
          <td id="id-{{d['id']}}">
            {{d['student_id']}}
          </td>
          <td id="name-{{d['id']}}">
            {{d['student_name']}}
          </td>
          <td id="dept-id-{{d['id']}}">
            {{d['dept_id']}}
          </td>
          <td id="dept-name-{{d['id']}}">
            {{d['department_name']}}
          </td>
          <td id="last-attendance-{{d['id']}}">
            {{d['latest_attendance']}}
          </td>
          <td id="attendance-count-{{d['id']}}">
            {{d['attendance_count']}}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No data available.</p>
  {% endif %}
</div>
{% endblock %}

HW2/templates/student.html
{% extends "main_layout.html" %}

{% block title %}Student{% endblock %}

{% block content %}
<div style="width: 80%; margin-top: 16px;">
  <h2>Student Info</h2>
  
  <div id="notification" style="display: none;"></div>
  <form id="form" method="POST" onsubmit="handleSubmitForm(event)">
    <div style="display: flex; align-content: center;">
      <div style="display: flex; gap: 16px;">
        <div>
          <label for="student_id">Student ID:</label>
          <input
            style="max-width: 200px;"
            class="input-field"
            type="text"
            id="student_id"
            name="student_id"
            required
          />
        </div>
        <div>
          <label for="name">Student name:</label>
          <input class="input-field" type="text" id="name" name="name" required />
        </div>
        <div>
          <label for="dept_id">Department ID:</label>
          <input
            style="max-width: 200px;"
            class="input-field"
            type="text"
            id="dept_id"
            name="dept_id"
            required
          />
        </div>
        <div>
          <label for="num_of_faculty">Date of birth:</label>
          <input class="input-field" type="date" id="dob" name="dob" required/>
        </div>
      </div>
      
    </div>
    <button class="submit-button" type="submit">Submit</button>
  </form>
  <br/>
  {% if students|length > 0 %}
    <table border="1" class="table-class">
      <thead>
        <tr>
          <td>ID</td>
          <td>Student ID</td>
          <td>Student name</td>
          <td>Department ID</td>
          <td>Date of Birth</td>
        </tr>
      </thead>
      <tbody>
        {% for student in students%}
        <tr>
          <td>{{loop.index}}</td>
          <td 
            id="id-{{student['id']}}"
            style="padding-right: 8px"
          >
            {{student['student_id']}}
          </td>
          <td 
            id="name-{{student['id']}}"
            style="padding-right: 8px; width: 160px;"
          >
            {{student['name']}}
          </td>
          <td id="dept-{{student['id']}}" style="width: 160px;">
            {{student['dept_id']}}
          </td>
          <td id="dob-{{student['id']}}">
            {{ student['dob'].strftime("%Y-%m-%d") }}
          </td>
          <td style="width: 50px; ">
            <div id="button-{{student['id']}}" style="display: flex; justify-content: space-between; justify-self: center;">
              <i 
                class="fa-regular fa-pen-to-square" 
                style="cursor: pointer; margin-right: 8px;" 
                type="button"
                onclick="onEditButtonClick('{{student['id']}}')"
              ></i>
              <i 
                class="fa-solid fa-trash"
                style="cursor: pointer;" 
                type="button"
                uk-toggle="target: #modal-center"
                onclick="storeRecordId('{{student['id']}}')"
              ></i>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No departments available.</p>
  {% endif %}
  <div id="modal-center" uk-modal>
    <div class="uk-modal-dialog uk-modal-body uk-margin-auto-vertical"">
      <h2 style="justify-self: center;">Delete this record?</h2>
      <p class="uk-text-right">
        <button class="uk-button uk-button-default uk-modal-close" type="button">Cancel</button>
        <button class="uk-button uk-button-danger" type="button" onclick="onDeleteButtonClick()">Delete</button>
      </p>
    </div>
  </div>
</div>

<script>
  var initButtonContainerInnerHTML;
  var initStudentIdRowInnerHTML;  
  var initNameRowInnerHTML;
  var initDeptIdRowInnerHTML;
  var initDobInnerHTML;
  var currentRecordId;

  function storeRecordId(id) {
    currentRecordId = id;
  }

  async function handleSubmitForm(event) {
    event.preventDefault(); // Prevent the form from submitting the traditional way

    const form = document.getElementById('form');
    const formData = new FormData(form);

    try {
      const response = await fetch(form.action, {
        method: 'POST',
        body: formData
      });

      if (!response.ok) {
        const errorData = await response.json();
        
        const notification = document.getElementById('notification');
        const studentIdContainer = document.getElementById('student_id');
        const deptIdContainer = document.getElementById('dept_id');
        const studentNameContainer = document.getElementById('name');
        const dobContainer = document.getElementById('dob');

        studentIdContainer.value = "";
        deptIdContainer.value = "";
        studentNameContainer.value = "";
        dobContainer.value = "";

        notification.style = `
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 10px;
          padding: 8px;
          background-color: rgb(255, 215, 222);
          color: red; 
          font-weight: bold;
        `;
        notification.innerHTML = `
          <p style="text-align: center; margin: 0 !important;">${errorData.error || 'An error occurred'}</p>
          <i 
            class="fa-regular fa-circle-xmark" 
            type="button"
            onclick="closeNotification()"
          ></i>
        `;
        // 
      } else {
        // If successful, reload the page or update the UI as needed
        window.location.href = "{{ url_for('student_routes.get_all_student_route') }}";
      }
    } catch (error) {
      notification.style.display = 'block';
      notification.innerText = 'An error occurred while submitting the form.';
      console.error('Submission error:', error);
    }
  }

  function closeNotification() {
    const notification = document.getElementById('notification');
    notification.style.display = 'none';
  }

  function onEditButtonClick(id) {
    const buttonContainer = document.getElementById("button-" + id);
    const studentIdRow = document.getElementById("id-" + id);
    const deptIdRow = document.getElementById("dept-" + id);
    const nameRow = document.getElementById("name-" + id);    
    const dobRow = document.getElementById("dob-" + id);

    initStudentIdRowInnerHTML = studentIdRow.innerHTML;
    initButtonContainerInnerHTML = buttonContainer.innerHTML;
    initDeptIdRowInnerHTML = deptIdRow.innerHTML;
    initNameRowInnerHTML = nameRow.innerHTML;
    initDobInnerHTML = dobRow.innerHTML;
   
    const date = new Date(dobRow.innerText);
    const month = String(date.getMonth() + 1).padStart(2, '0'); // Months are zero-based
    const day = String(date.getDate()).padStart(2, '0');
    const year = date.getFullYear();
    const formattedDate = `${year}-${month}-${day}`;

    buttonContainer.innerHTML = `
      <i 
        class="fa-solid fa-check"
        style="cursor: pointer; margin-right: 8px" 
        type="button"
        onclick="submitEdit(${id})"
      ></i>
      <i 
        class="fa-solid fa-xmark"
        style="cursor: pointer;" 
        type="button"
        onclick="closeEdit(${id})"
      ></i>
    `;

    studentIdRow.innerHTML = `
      <input 
        style="width: 120px;"
        class="input-field"
        type="text" 
        id="id-input-${id}" 
        value="${studentIdRow.innerText}"
      >
    `;

    nameRow.innerHTML = `
      <input 
        style="width: 160px;"
        class="input-field"
        type="text" 
        id="name-input-${id}" 
        value="${nameRow.innerText}"
      >
    `;

    deptIdRow.innerHTML = `
      <input 
        style="width: 100px;"
        class="input-field"
        type="text" 
        id="dept-input-${id}" 
        value="${deptIdRow.innerText}"
      >
    `;

    dobRow.innerHTML = `
      <input 
        style="width: 120px;"
        class="input-field"
        type="date" 
        id="dob-input-${id}" 
        value="${formattedDate}"
      >
    `; 
  }

  function submitEdit(id) {
    const buttonContainer = document.getElementById("button-" + id);
    const studentId = document.getElementById("id-input-" + id).value;
    const deptId = document.getElementById("dept-input-" + id).value;
    const name = document.getElementById("name-input-" + id).value;
    const dob = document.getElementById("dob-input-" + id).value;

    $.ajax({
      url: "/student/update/" + id,
      type: "PUT",
      contentType: "application/json",
      data: JSON.stringify({
        student_id: studentId,
        dept_id: deptId,
        name: name,
        dob: dob
      }),
      success: function () {
        location.reload();
        // alert("Attendance updated successfully!");
      },
      error: function (err) {
        const notification = document.getElementById('notification');
        notification.style = `
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 10px;
          padding: 8px;
          background-color: rgb(255, 215, 222);
          color: red; 
          font-weight: bold;
        `;

        notification.innerHTML = `
          <p style="text-align: center; margin: 0 !important;">${err.responseJSON.error || 'An error occurred'}</p>
          <i 
            class="fa-regular fa-circle-xmark" 
            type="button"
            onclick="closeNotification()"
          ></i>
        `
        closeEdit(id);
      },
    });
  }

  function closeEdit(id) {
    const buttonContainer = document.getElementById("button-" + id);
    const studentIdRow = document.getElementById("id-" + id);
    const deptIdRow = document.getElementById("dept-" + id);
    const nameRow = document.getElementById("name-" + id);    
    const dobRow = document.getElementById("dob-" + id);

    buttonContainer.innerHTML = initButtonContainerInnerHTML;
    studentIdRow.innerHTML = initStudentIdRowInnerHTML;
    deptIdRow.innerHTML = initDeptIdRowInnerHTML;
    nameRow.innerHTML = initNameRowInnerHTML;
    dobRow.innerHTML = initDobInnerHTML;
  }

  function onDeleteButtonClick() {
    $.ajax({
      url: "/student/delete/" + currentRecordId,
      type: "DELETE",
      contentType: "application/json",
      success: function () {
        location.reload();
        // alert("Attendance deleted successfully!");
      },
      error: function (err) {
        alert("Error: Student delete failed!");
        console.error("Error deleting student:", err);
      },
    });
  }
</script>
{% endblock %}